blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('contact', views.contact, name='contact'),
    path('skill', views.skill, name='skill')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from blog.form import ContactForm
import sys
from django.core.mail import send_mail, EmailMessage
import smtplib
from blog.mail_submit import create_message


ACCOUNT = "ryuichi.umehara.miraidenshi@gmail.com"
ALIAS = "ryuihi-astrona@ymobile.ne.jp"
PASSWORD = "Ryuichi7"



# Create your views here.


def post_list(request):
    return render(request, 'blog/post_list.html', {})
    if (request.method == 'POST'):
        subject=request.POST['subject']
        message=request.POST['message']
        from_email = settings.EMAIL_HOST_USER
        recipient_list = [
        "ryuichi-astrona@ymobile.ne.jp"
        ]
        send_mail(subject, message, from_email, recipient_list)
        # msg = create_message(subject,message,sender)

        # s = smtplib.SMTP("smtp.gmail.com", 587)
        # s.ehlo()
        # s.starttls()
        # s.ehlo()
        # s.login(ACCOUNT, PASSWORD)

        # s.sendmail(ACCOUNT, ALIAS, msg.as_string())
        # s.quit()
        # print("postと認識されている")

def contact(request):
    form = ContactForm()
    return render(request, 'blog/contact.html', {
        'form': form.as_table(),
    })


def skill(request):
    return render(request,'blog/skill.html',{})




blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"ja" }}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    {% block extra_css %}{% endblock %}
    <title>{% block title %}My books{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        /*imgの大きさを設定するクラス heightを指定しないと次へのボタンの位置が変わる */
        .carousel-inner>.item>img,
        .carousel-inner>.item>a>img {
            margin: auto;
            height: 300px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar">i</span>
                    <span class="icon-bar">u</span>
                </button>
                <a class="navbar-brand" href="#">逆採用ページ</a>

            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    {% block extra_js %}{% endblock %}
</body>

</html>

blog/templates/blog/contact.html
{% extends "blog/base.html" %} {% block content %}
<form method="post" action="{% url 'blog:post_list' %}">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <!-- <label>件名</label><br />
  <input
    type="text"
    name="subject"
    maxlength="100"
    value=""
    placeholder="１００文字以内で入力"
  /><br />
  <label>内容</label><br />
  <input
    type="text"
    name="message"
    maxlength="1000"
    value=""
    placeholder="１０００文字以内で入力"
  /><br />
  <label>お名前</label><br />
  <input
    type="text"
    name="sender"
    maxlength="100"
    value=""
    placeholder="フルネーム"
  /><br /> -->

    <input type="submit" value="送信" />
</form>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
{% load static %}

<div id="carousel-sample" class="carousel slide" data-ride="carousel" data-interval="3000">
    <!-- 以下は画像下部の○○○の部分の設定-->
    <!-- class="active"で初期に表示される画像を設定している-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-sample" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-sample" data-slide-to="1"></li>
        <li data-target="#carousel-sample" data-slide-to="2"></li>
    </ol>

    <!--画像スライドの中身-->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <a href='/'><img src="{% static 'home.png'%}" alt="..."></a>
            <div class="carousel-caption">
                <!--画像の説明 -->
                <h1>梅原　隆一</h1>
                <p>雇ってみませんか？</p>
            </div>
        </div>
        <div class="item">
            <a href="/skill"><img src="{% static 'skill.jpg'%}" alt="..."></a>
            <div class="carousel-caption">
                <h1>スキル</h1>
            </div>
        </div>

        <div class="item">
            <a href="/contact"><img src="{% static 'contact.jpeg'%}" alt="..."></a>
            <div class="carousel-caption">
                <h1>お問い合わせ</h1>
            </div>
        </div>

    </div>

    <!-- 左 右の矢印の設定 -->
    <a class="left carousel-control" href="#carousel-sample" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">戻る</span>
    </a>
    <a class="right carousel-control" href="#carousel-sample" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">次へ</span>
    </a>
</div>
<a class="twitter-timeline" href="https://twitter.com/astrona0626?ref_src=twsrc%5Etfw">Tweets by astrona0626</a>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
{% endblock content %}

blog/templates/blog/skill.html
{% extends "blog/base.html" %}
{% block content %}
<h1>動画編集</h1>
<h3>梅原は動画編集技術を持っています。学園祭のミニドラマの製作部長として、<br>クロマキー処理などの難しい編集も独学で勉強し、完成させました。<br>また、今年の滋賀県近江八幡市成人式でも、梅原の編集した、ビデオが流れました</h3>
<hr>
<h1>バスケ</h1>
<h3>梅原はバスケを中学から6年間やっています。バスケはしんどいスポーツですが、<br>運動することが好きなので、大学生になった今でもサークルで続けています</h3>
<hr>
<h1>プログラミング</h1>
<h3>梅原はプログラミングもできます。歴としては3か月程度ですが、この前、<br>サークルの体育館を予約するプログラムを作成して、部員からとても感謝されました！</h3>
{% endblock content %}